// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nidacqaqhfhcprluoodq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5pZGFjcWFxaGZoY3BybHVvb2RxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MTg4MDksImV4cCI6MjA2NTQ5NDgwOX0.uPdxO0l2D8Vy1d6OrRhwrATu4YkJm_ozQO9WjBjGTgg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});